### ISSUE TITLE
Consensus issue

### ISSUE THREAD

**Issue by faridrashidi** [faridrashidi/trisicell#20]
### Description

Error when trees have different cells

### Minimal reproducible example

```python
trisicell consensus example_input_1.CFMatrix example_input_2.CFMatrix output.CFMatrix
```
### Traceback

<details>
```pytb
Traceback (most recent call last):
  File "run_trisicell.py", line 18, in <module>
    tsc.tl.consensus_tree(matrix_1, matrix_2)
  File "/u/smalikic/anaconda3/lib/python3.8/site-packages/trisicell/tl/consensus/_consensus.py", line 209, in consensus_tree
    common_cells = list(np.intersect1d(nodes1.keys(), nodes2.keys())[0])
IndexError: index 0 is out of bounds for axis 0 with size 0
```
</details>

### Version

...

**Comment by faridrashidi** [comment]
closed via #21
